library(sf)
library(rgdal)
library(dplyr)
library(plyr)
library(readr)
library(raster)
library(bcmaps)
library(bcdata)
library(fasterize)
library(tidyr)
#library(rio)
library(WriteXLS)
library(ggplot2)
library(readxl)
library(stringr)
library(mapview)
#library(gdata)
#library(reshape2)
library(stars)
library(exactextractr)
library(terra)
library(data.table)

library(randomForest)
library(datasets)
library(caret)
library(partykit)
library(fuzzyjoin)
library(lubridate)
library(spatstat)
library(gstat) 
library(sp) 
library(SpatialTools)
library(spdep)
library(spatialEco)

#added by Gen P.
#library(plotKML)
library(purrr)
library(lubridate)
library(tibble)
library(janitor)
library(foreign)
library(magrittr)
library(spdep)
library(ggnewscale)
library(exactextractr)

